### ISSUE TITLE
Field "description"  is unsupported at service template level

### ISSUE THREAD

**Issue by abhishek-kumar0409** [tliron/puccini#10]
tosca_definitions_version: tosca_simple_yaml_1_2
**description: A test description message**            # comment:  the description field here is unsupported in puccini. This was well supported in ARIA.

topology_template:
      ....
      ....

**Errror output**

PROBLEMS (1)
  file:/puccini/examples/grammar/substitution-mapping.yaml
    description: field is unsupported

**Comment by tliron** [comment]
Thank you, this was an oversight and will be fixed.
