### ISSUE TITLE
Working with Kubernetes volumes

### ISSUE THREAD

**Issue by codesnk** [tliron/puccini#11]
I have a very basic, sample kubernetes service for prototyping (given below) that works with K8S but uses "hostPath" volume type. I wanted to create a tosca template for this service which, when compiled with puccini, should give me the same type of service deployment for kubernetes. Looking at the source, it seems that the Kubernetes yaml spec in puccini is probably not supporting volumes of this kind. If my understanding is correct, this probably means I have to add the missing parts. The current development guide on the repo does not talk about how to extend puccini by contributing missing functionality. Can you provide me some guidelines on how to get my intended demo working i.e., starting from a tosca profile to get the given k8s deployment. Thanks.

> apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamer
  labels:
    app: streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer
  template:
    metadata:
      labels:
        app: streamer
    spec:
      containers:
      - name: vlcstreamer
        image: shazmailz/vlcstreamer
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /data
          name: videofolder
      volumes:
      - name: videofolder
        hostPath:
          path: /home/shah/videos
kind: Service
apiVersion: v1
metadata:
  name: streamer
spec:
  type: NodePort
  selector:
    app: streamer
  ports:
  - nodePort: 31001
    protocol: TCP
    port: 9000
    targetPort: 80

**Comment by tliron** [comment]
You are right, Puccini is still at an early stage and many features are not supported yet. But it shouldn't be too hard to add them ... Do you want to try adding them yourself?

**Comment by codesnk** [comment]
Since I am experimenting with Puccini, I might as well try to do that. But I need some pointers on how to do that. I am comfortable with K8S and Golang but not so much with Pure/Standard Tosca. From my initial understanding from the code, you seem to have created Tosca yaml definitions for Kubernetes resources. Do you think you may be able to update the developer's guide with a paragraph on how to extend puccini for kuberentes/Openstack specific resources e.g. volumes.

**Comment by tliron** [comment]
I appreciate your attempt, and will be happy to help!

I imagine you won't need to do any Go coding at all (unless you find bugs). The main work would be first to add the [TOSCA models](https://github.com/tliron/puccini/tree/master/assets/tosca/profiles/kubernetes/1.0) for all the missing Kubernetes resources (volumes in this case). You will have to think a bit on the best way to model them. I am thinking that they are probably best designed as nodes, with relationships to other nodes. You will then have to add the [JavaScript code](https://github.com/tliron/puccini/blob/master/assets/tosca/profiles/kubernetes/1.0/js/generate.js) to generate the right Kubernetes specs for these resources.

You would then have to run `embed.sh` to get these YAML and JS files into Go, and then `build.sh` (or your own build process). More details [here](https://github.com/tliron/puccini/blob/master/scripts/README.md).

**Comment by codesnk** [comment]
OK. I think I was following the right path. Since it is not an issue with Puccini per se, I will close this thread. Meanwhile, I will work on it and if I found it useful, may send a pull request. Cheers.
