### ISSUE TITLE
Issue with the scripts 

### ISSUE THREAD

**Issue by codesnk** [tliron/puccini#14]
I pulled the master branch today and with some of the scripts in the scripts folder i got:

"/bin/bash^M: bad interpreter: No such file or directory**"

Couldn't confirm if this is the windows/linux line-ending issue.

**Comment by tliron** [comment]
Can you let me know what environment (operating system, terminal, shell) you are running in? And which specific scripts failed?

**Comment by codesnk** [comment]
Tried it on Xubuntu Linux with zsh. I probably checked embed.sh which worked. enusre.sh and one other failed with that message.

**Comment by codesnk** [comment]
Tried on another linux machine and there is no problem here. Must be an issue with that PC. Sorry for being hasty in opening an issue.
