### ISSUE TITLE
multiple definitions of -p flag

### ISSUE THREAD

**Issue by codesnk** [tliron/puccini#26]
Hi,

noticed that the parse command fails to run because "-p" has been used for both "pretty" and "print" in puccini-tosca. Changing one of those solves the issue.

**Comment by tliron** [comment]
Thanks! I somehow missed this one during testing. I took the opportunity to look at the switches again and made some changes, see the [readme](https://github.com/tliron/puccini/blob/master/puccini-tosca/README.md).
