### ISSUE TITLE
Add support for workflow filters

### ISSUE THREAD

**Issue by pmjordan** [tliron/puccini#27]
If I add the a filter clause taken from TOSCA 1.3 para 7.3 after line 42 of examples/Tosca/workflows.yaml
the parser gives an error 
topology_template.workflows["backup"].steps["notify_users"].filter[0] @44,15: malformed "constraint clause", unsupported operator: or

          filter: # filter is a list of clauses. Matching between clauses is and.
            - or: # only one of sub-clauses must be true.
              - assert:
                - foo: [{equals: true}]
              - assert:
                - bar: [{greater_than: 2}, {less_than: 20}]

This appears to indicate that workflow filters are not parsed by release 0.9

**Comment by tliron** [comment]
Thanks! This is an oversight due to an error in the spec. In the table in 3.6.27 it shows "filter" as constraint clauses, but actually it should be condition clauses. I will fix this.

Note that TOSCA 1.3 condition clauses are parsed, but not yet fully validated in Puccini... workflows in general are a work in progress, and actually there is some discussion in the TOSCA TC about major changes to the grammar.

**Comment by pmjordan** [comment]
Sorry to doubt you but my test of release 0.10 on your new version of examples/Tosca/workflows.yaml still gives an error of 

topology_template.workflows["backup"].steps["notify_users"].filter[0] @49,13: malformed "constraint clause", unsupported operator: or

**Comment by tliron** [comment]
I just downloaded it and tested it and does work (linux x64). Are you sure you are using the right executable and the right example?

BTW, I'm glad you prompted this, because I noticed the release tar.gz has the example directories, but no files. I will fix that for future releases.

**Comment by tliron** [comment]
So, I just released 0.11.0 that also includes the examples. Could you please confirm it works for you?

**Comment by pmjordan** [comment]
Completely my fault. I had an issue with a simlink and hence have submitted issue #24. Thanks for including the examples, I had assumed that they were omitted deliberately.
