### ISSUE TITLE
Include build number in version string

### ISSUE THREAD

**Issue by pmjordan** [tliron/puccini#28]
It would be helpful to be able to confirm the puccini version by consulting the output of the version command. In version 0.11.0 the output is 

$ ./puccini-tosca version
arch=amd64
os=windows
compiler=gc

I suggest a further line showing something like
release=0.11.0

**Comment by tliron** [comment]
Thanks, these versions do appear when you build locally using the scripts, it seems to be an issue with goreleaser ... I will look into it!

**Comment by tliron** [comment]
Released [v0.11.1](https://github.com/tliron/puccini/releases/tag/v0.11.1) with this fixed.
