### ISSUE TITLE
puccini-tosca: command not found

### ISSUE THREAD

**Issue by dorrachaari** [tliron/puccini#31]
I'm following the the quickstart https://puccini.cloud/QUICKSTART.html 
When I run the command puccini-tosca compile examples/kubernetes/bookinfo/bookinfo-simple.yaml | puccini-js exec kubernetes.generate | kubectl apply -f -
 I keep getting this error 
puccini-tosca: command not found
puccini-js: command not found
error: no objects passed to apply

**Comment by tliron** [comment]
You need the executables to be in your execution path. If you are on Linux this should work for the session:
```
export PATH=$PATH:~/go/bin/
```
Or, you can copy them to `/usr/bin/`.

**Comment by dorrachaari** [comment]
I am not sure what executables you're talking about but I downloaded puccini-master from here https://github.com/tliron/puccini and I extracted it in home then I copied the folders puccini-js and puccini-tosca folders in /usr/bin/. 
I ran the dashboard in one terminal and then the command puccini-tosca compile examples/kubernetes/bookinfo/bookinfo-simple.yaml | puccini-js exec kubernetes.generate | kubectl apply -f - in another terminal and I still get the same error.

**Comment by tliron** [comment]
I think you downloaded the source code, in which case you would have to build the executables yourself following the [build guide](https://github.com/tliron/puccini/blob/master/scripts/README.md). But you don't have to do that. You can download pre-compiled executables.

Go to the [download](https://github.com/tliron/puccini/releases) page (linked from the nice big green "download" button on the Puccini site), and you'll see it organized by tags. The latest release at the moment is v0.13.0. In that section you will see "Assets", which are named according to platform. If you're on Windows, pick the "windows_amd64.zip" file. If you're on Mac, pick the "darwin_amd64.tar.gz" file. For Linux there is a "tar.gz" file as well as ".deb" and ".rpm" packages.

**Comment by dorrachaari** [comment]
Thanks it's working completely fine now.
