### ISSUE TITLE
Parser does not include implementation defined in interface type

### ISSUE THREAD

**Issue by pmjordan** [tliron/puccini#32]
In examples/tosca/interfaces.yaml, if line 112 'implementation: /opt/scripts/maintenance_off.sh' is moved to after line 64 so that the implementation is declared in the type rather than in the node template, then the output of the parse operation does not include the string maintenance_off.sh.
Tosca 1.3 para 3.6.17 states that implementation may be defined in the operation section of an interface type definition.
This issue is low priority for me.

**Comment by tliron** [comment]
Good catch and good problem description!
