### ISSUE TITLE
node_filter example fails validation

### ISSUE THREAD

**Issue by pmjordan** [tliron/puccini#34]
Attempting to parse example 12 from TOSCA simple profile1.3 results in an error 
@19,9 topology_template.node_templates["mysql_compute"].node_filter.capabilities: "!!seq" instead of "!!map"

Obviously I first commented out the sections which caused errors because parts were omitted for brevity. I attach my test file below with file extension changed from yml to txt so that it can be submitted to github

[example12.txt](https://github.com/tliron/puccini/files/4629573/example12.txt)

**Comment by tliron** [comment]
You are correct, this is a bug, thanks. Will submit a fix soon.
