### ISSUE TITLE
Support metada on topology template elements

### ISSUE THREAD

**Issue by loicalbertin** [tliron/puccini#39]
Metadata are currently not supported on [nodes templates](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#DEFN_ENTITY_NODE_TEMPLATE), [relationships templates](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#DEFN_ENTITY_RELATIONSHIP_TEMPLATE), [groups definitions](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#DEFN_ELEMENT_GROUP_DEF) and [policies definitions](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#DEFN_ELEMENT_POLICY_DEF) while according to TOSCA 1.3 it should be supported.

Could you please consider adding support of these fields?

**Comment by tliron** [comment]
Thank you, you are absolutely right. This feature was added in TOSCA 1.1 and I somehow managed to miss it...

**Comment by loicalbertin** [comment]
Great! Thanks

**Comment by loicalbertin** [comment]
Hi @tliron 

don't you think it could make sense to enable the `data_types.string.permissive` quirk on metadata values?

I sometimes have those kind of metadata:

```yaml
topology_template:
  node_templates:
    ComputeSlurmCtl:
      metadata:
        a4c_edit_x: 501
```

Puccini returns the following error:

```bash
            @57,9 topology_template.node_templates["ComputeSlurmCtl"].metadata["a4c_edit_x"]: "ard.integer" instead of "ard.string"
```

**Comment by tliron** [comment]
You are right, this was an omission. It is also an opportunity to improve some of the code for parsing generic YAML maps.

Thank you for all your issue reports!

**Comment by tliron** [comment]
I'm about to make a commit. Notes:

* Actually, the quirk will now affect not just the value, but also the key (YAML allows keys to be any arbitrary value)
* Be careful with this quirk! A value such as an unquoted "1.0" (a float) would be stringified as "1". I recommend not using this quirk if at all possible.

**Comment by loicalbertin** [comment]
Yeah I know that's dangerous, but I depend on something that could produce things as strange as this:

```yaml
    ComputeSlurmCtl:
      metadata:
        a4c_edit_x: 501
        a4c_edit_y: "-109"
```

**Comment by tliron** [comment]
Is it possible that your "something" could wrap everything in quotation marks before embedding in TOSCA?
