### ISSUE TITLE
Support entry_schema in list datatype defintions.

### ISSUE THREAD

**Issue by pmjordan** [tliron/puccini#40]
TOSCA 1.3 para 3.8.6.3 seems to suggest that entry_schema can be defined within a data type definition.
I added the following to line 156 of examples/tosca/data-types.yaml

  LowerCaseList:
    derived_from: list
    entry_schema: LowerCase

but a puccini parse gives the error

@158,5 data_types["LowerCaseList"].entry_schema: unsupported field

**Comment by tliron** [comment]
Thanks! You are correct, this feature is missing. Will work on adding it.
