### ISSUE TITLE
Support outputs in operation defintion

### ISSUE THREAD

**Issue by pmjordan** [tliron/puccini#41]
TOSCA 1.3 para 3.7.11.1 appears to allow operations which occur in a node type definition to contain the outputs keyword.
When I add the following two blocks of code to examples/tosca/interfaces.yaml

line 83 
      attributes:
        maintenance_mode_off_response_time: integer
new line 117 (after priority: .75)
              outputs:
                time_taken: SELF, maintenance_mode_off_response_time

then I get the following parse error 
@117,15 topology_template.node_templates["server"].interfaces["Maintenance"].operations["maintenance_off"].outputs: unsupported field

**Comment by 117** [comment]
I agree. (;

**Comment by tliron** [comment]
Apparently you missed the big TODO comment in the code about this. :) Well, now that somebody actually needs this I guess it's time to implement the feature!

**Comment by pmjordan** [comment]
Just to clarify -  I now understand that outputs may also be defined within interface operation definitions. I trust that your feature implementation will also include that syntax.

**Comment by tliron** [comment]
@pmjordan Sorry, just got to this now -- are you sure about interface outputs? I do not see that in the 1.3 specification.

**Comment by pmjordan** [comment]
I'm referring to 3.6.17.1. i.e.
interface
   operation
      outputs

(3.6.17.2.2 appears to have a error where the outputs keyword is indented too much)

**Comment by tliron** [comment]
OK, yes, I was confused by how you described it. To be clear:

You can define outputs on _operations_, in types (definitions) and in templates (assignments).

However for the interface itself you can only define inputs.
