### ISSUE TITLE
Primitive data types missing from v2

### ISSUE THREAD

**Issue by pmjordan** [tliron/puccini#43]
Not sure if it is really fair yet to submit issues on your support for v2 but I notice if I change the version string to tosca_2_0 in examples/tosca/data-types.yaml then the parser errors at each mention of a primitive datatype.

$ puccini-tosca parse data-typesv2.yaml
PROBLEMS (37)
  
    @134,9 data_types["Complex"].properties["float"].type: reference to unknown data type: float
    @132,9 data_types["Complex"].properties["integer"].type: reference to unknown data type: integer
    @128,9 data_types["Complex"].properties["string"].type: reference to unknown data type: string
    @154,5 data_types["LowerCase"].derived_from: reference to unknown data type: string
    @144,9 data_types["Nested"].properties["nested_float"].type: reference to unknown data type: float
    @148,9 data_types["Nested"].properties["nested_string"].type: reference to unknown data type: string
    @160,5 data_types["TimeMap"].derived_from: reference to unknown data type: map
    @163,5 data_types["TimeMap"].entry_schema.type: reference to unknown data type: scalar-unit.time
    @25,9 node_types["DataNode"].properties["boolean"].type: reference to unknown data type: boolean
    @45,9 node_types["DataNode"].properties["complex_list"].type: reference to unknown data type: list
    @98,11 node_types["DataNode"].properties["constrained_float_list"].entry_schema.type: reference to unknown data type: float
    @96,9 node_types["DataNode"].properties["constrained_float_list"].type: reference to unknown data type: list
    @76,9 node_types["DataNode"].properties["constrained_string"].type: reference to unknown data type: string
    @105,9 node_types["DataNode"].properties["constrained_time"].type: reference to unknown data type: scalar-unit.time
    @111,9 node_types["DataNode"].properties["constrained_version"].type: reference to unknown data type: version
    @22,9 node_types["DataNode"].properties["float"].type: reference to unknown data type: float
    @20,9 node_types["DataNode"].properties["integer"].type: reference to unknown data type: integer
    @34,9 node_types["DataNode"].properties["integer_list"].entry_schema.type: reference to unknown data type: integer
    @33,9 node_types["DataNode"].properties["integer_list"].type: reference to unknown data type: list
    @68,9 node_types["DataNode"].properties["json"].type: reference to unknown data type: tosca.datatypes.json
    @91,9 node_types["DataNode"].properties["lowercase_string_map"].entry_schema.type: reference to unknown data type: string
    @89,9 node_types["DataNode"].properties["lowercase_string_map"].type: reference to unknown data type: map
    @29,9 node_types["DataNode"].properties["null"].type: reference to unknown data type: null
    @63,9 node_types["DataNode"].properties["range"].type: reference to unknown data type: range
    @57,9 node_types["DataNode"].properties["scalar_unit_bitrate"].type: reference to unknown data type: scalar-unit.bitrate
    @55,9 node_types["DataNode"].properties["scalar_unit_frequency"].type: reference to unknown data type: scalar-unit.frequency
    @51,9 node_types["DataNode"].properties["scalar_unit_size"].type: reference to unknown data type: scalar-unit.size
    @53,9 node_types["DataNode"].properties["scalar_unit_time"].type: reference to unknown data type: scalar-unit.time
    @18,9 node_types["DataNode"].properties["string"].type: reference to unknown data type: string
    @37,9 node_types["DataNode"].properties["string_map"].entry_schema.type: reference to unknown data type: string
    @36,9 node_types["DataNode"].properties["string_map"].type: reference to unknown data type: map
    @59,9 node_types["DataNode"].properties["timestamp"].type: reference to unknown data type: timestamp
    @61,9 node_types["DataNode"].properties["version"].type: reference to unknown data type: version
    @70,9 node_types["DataNode"].properties["xml"].type: reference to unknown data type: tosca.datatypes.xml
    @270,9 topology_template.node_templates["data"].properties["lowercase"]: "string" instead of "map"
    @286,11 topology_template.node_templates["data"].properties["time_map"]["first"]: undeclared property
    @287,11 topology_template.node_templates["data"].properties["time_map"]["second"]: undeclared property

**Comment by tliron** [comment]
2.0 support really is just beginning, but I appreciate this bug report!
