### ISSUE TITLE
Question about using Puccini from Go code

### ISSUE THREAD

**Issue by amarchese96** [tliron/puccini#44]
Hi,
in the documentation, you have said that it is possible to use Puccini directly from a program written in Go. But I didn't understand very well what is the best way to use Puccini as a library in a Go program. Is it right to invoke functions inside the packages "github.com/tliron/puccini/puccini-tosca/commands" and "github.com/tliron/puccini/puccini-clout/commands"? Or maybe I have to use packages like "github.com/tliron/puccini/tosca/compiler" and "github.com/tliron/puccini/clout"?
Thanks.

**Comment by tliron** [comment]
Indeed Puccini is still not 1.0 and one of the big things missing is API documentation...

For now I would recommend as a starting point to look at [library.go](https://github.com/tliron/puccini/blob/main/puccini-tosca/library.go). This code is used to export the core functionality to C (for use by the Python/Java/Ruby wrappers), but as such you can see the main usage flow: creating a URL, parsing TOSCA (turning it into normalized structures), compiling it to Clout, and optionally resolving requirements and coercing values. If you use a good Go IDE then you would be able to easily follow every API call with a click and learn more. The parsing call is the most complex, as inside you will see the multiple phases used to interpret the TOSCA grammars.

I will keep this issue open. If you have more questions I will be happy to point you in the right direction.

**Comment by amarchese96** [comment]
Thank you for the help.
I tried to write a simple program based on library.go code, but  I have some problems with the dependencies. In my go.mod file I have the following dependencies:

- github.com/tliron/kutil v0.1.22
- github.com/tliron/puccini v0.17.0

When I try to compile the program I get the following errors:

# github.com/tliron/puccini/clout
../go/pkg/mod/github.com/tliron/puccini@v0.17.0/clout/clout.go:90:3: cannot use map_ (type interface {}) as type map[interface {}]interface {} in return argument: need type assertion
../go/pkg/mod/github.com/tliron/puccini@v0.17.0/clout/decode.go:25:21: undefined: ard.ToStringMap
../go/pkg/mod/github.com/tliron/puccini@v0.17.0/clout/decode.go:33:23: undefined: ard.ToStringMap
../go/pkg/mod/github.com/tliron/puccini@v0.17.0/clout/decode.go:48:27: undefined: ard.ToStringMap
../go/pkg/mod/github.com/tliron/puccini@v0.17.0/clout/decode.go:56:29: undefined: ard.ToStringMap
../go/pkg/mod/github.com/tliron/puccini@v0.17.0/clout/decode.go:72:31: undefined: ard.ToStringMap
../go/pkg/mod/github.com/tliron/puccini@v0.17.0/clout/decode.go:80:33: undefined: ard.ToStringMap

**Comment by amarchese96** [comment]
Thank you for the help. I tried to write a simple program based on the steps of library.go code, but I have some problems with the dependencies. The content of my go.mod file is the following:

```
module example.com/puccini

go 1.16

require (
	github.com/tliron/kutil v0.1.22
	github.com/tliron/puccini v0.17.0
)
```
When I try to compile the program I get the following errors:

```
github.com/tliron/puccini/clout
../go/pkg/mod/github.com/tliron/puccini@v0.17.0/clout/clout.go:90:3: cannot use map_ (type interface {}) as type map[interface {}]interface {} in return argument: need type assertion
../go/pkg/mod/github.com/tliron/puccini@v0.17.0/clout/decode.go:25:21: undefined: ard.ToStringMap
../go/pkg/mod/github.com/tliron/puccini@v0.17.0/clout/decode.go:33:23: undefined: ard.ToStringMap
../go/pkg/mod/github.com/tliron/puccini@v0.17.0/clout/decode.go:48:27: undefined: ard.ToStringMap
../go/pkg/mod/github.com/tliron/puccini@v0.17.0/clout/decode.go:56:29: undefined: ard.ToStringMap
../go/pkg/mod/github.com/tliron/puccini@v0.17.0/clout/decode.go:72:31: undefined: ard.ToStringMap
../go/pkg/mod/github.com/tliron/puccini@v0.17.0/clout/decode.go:80:33: undefined: ard.ToStringMap

```

**Comment by tliron** [comment]
Thanks for letting me know! People have not been using the Go API much, so I have been sloppy about tagging ...

I just tagged puccini 0.17.1 which should fix this problem.

**Comment by amarchese96** [comment]
Yes now it works. Thank you very much
