### ISSUE TITLE
Problems with Dgraph example

### ISSUE THREAD

**Issue by amarchese96** [tliron/puccini#45]
I tried executing the Dgraph example running a Dgraph database instance inside a container.

First, in the scriptlet "dgraph.js" I changed the imported scriptlet "tosca.utils" with "tosca.lib.traversal" because I get an error when I try to execute the scriptlet.

Second, I added the header "Content-Type: application/json" in the POST request in the file "export" because I get an error about supported formats.

Looking at the command output, it seems that the data are uploaded in the database but I can't see any data (maybe I'm not doing the correct query)

**Comment by tliron** [comment]
Thanks for this! The Dgraph example currently doesn't have an integration test so it indeed will accrue bugs... Let me look at it again and see what I can do to fix it.

**Comment by tliron** [comment]
So, I upgraded to the latest version of Dgraph and indeed many things have changed...

The example now "works", but I'm honestly not an expert in Dgraph and can really use help in making it better. Any feedback or contributions would be appreciated!

**Comment by amarchese96** [comment]
Thank you for the help. I'm not sure but I think there is a little problem with the schema fields (I state that I am also not an expert on Dgraph).

In Ratel UI I executed the query that is present in the file "export":

```
query{
  nodeTemplates(func: has(tosca.name)) {
   tosca.name
 }
}
```
and I see the nodes.

In order to see also the edges I added the field "clout:edge":

```
query{
  nodeTemplates(func: has(tosca.name)) {
   tosca.name
   clout:edge {
      tosca.name
   }
 }
}
```
but the attribute "clout:edge" is not returned in the query and I don't see the edges. I changed the query searching for nodes that have the attribute "clout:edge" (I tried also with "clout:vertex") but I get an error, maybe because the character ":" is used for function definition (I tried also with quotes but it doesn't work). To solve the problem I changed in file "dgraph.js" the fields "clout:vertex" and "clout:edge" with "clout_vertex" and "clout_edge" and now it works using the new fields.

Thanks again for the help.

**Comment by tliron** [comment]
Looks like we're both fumbling a bit here. :) I think the issue is that I'm not generating a schema at all. To be honest, I'm not sure if a schema is really necessary for queries. I assumed it was needed for validation and indexing. Yes, I also noticed that the colon was causing problems (by the way, in the older version of Dgraph I was targeting originally there was no problem with the colon.)

If you make any progress, please submit a pull request or just let me know here and I will commit it!

**Comment by amarchese96** [comment]
Ok thank you very much!!

**Comment by tliron** [comment]
Closed for now. Feel free to re-open or open a more specific issue if it comes up!
