### ISSUE TITLE
Add kubernetes.update script

### ISSUE THREAD

**Issue by tliron** [tliron/puccini#5]

**Comment by edwardchoh** [comment]
This would be useful. Otherwise, can you share how the update script should work?

How does the script set the right attribute values under the vertex, and output the modified clout?

Thanks.

**Comment by edwardchoh** [comment]
Would something like this work, to update the `public_address` attribute?

```
'use strict';

clout.exec('tosca.utils');

tosca.coerce();

writeAttributes();

function writeAttributes() {
	var template_name = clout.properties.tosca.metadata.template_name;

	for (var vertexId in clout.vertexes) {
		var vertex = clout.vertexes[vertexId];
		if (!tosca.isNodeTemplate(vertex))
			continue;
		var nodeTemplate = vertex.properties;
		if (nodeTemplate.attributes && 'public_address' in nodeTemplate.attributes) {
			// update the public_address value
			nodeTemplate.attributes.public_address = '8.8.8.8';
		}
	}

	puccini.write(clout);
}
```

**Comment by tliron** [comment]
Thanks, this is not a bad start. However I'm hoping to actually extract this from Kubernetes directly. :) For testing it could be via `kubectl`, but I imagine a real orchestrator would want to have a specialized Kubernetes operator that responds to change events and updates the database.

By the way, no need for `use strict` because the JavaScript environment is created with it automatically. I found some odd little scope bugs here and there and strict mode was a great way to find them. We're all better off with it enabled!

**Comment by edwardchoh** [comment]
Ok thanks, this gives me a starting point to build upon.

**Comment by tliron** [comment]
Moved to Turandot
