### ISSUE TITLE
Kubernetes profile

### ISSUE THREAD

**Issue by amarchese96** [tliron/puccini#63]
I don't see anymore the Kubernetes profile. Do I have to refer to the Kubernetes profile present in the Turandot repository?

**Comment by tliron** [comment]
That is correct. It made little sense to maintain the same code in two places. If you like, can refer in your imports directly to the raw URL on github: https://raw.githubusercontent.com/tliron/turandot/main/assets/tosca/profiles/kubernetes/1.0/profile.yaml
