### ISSUE TITLE
Problem with the examples

### ISSUE THREAD

**Issue by codesnk** [tliron/puccini#8]
I am new to learning tosca and it seems the bookinfo example is not working as expected. The output I get for the bookinfo compilation example is: 

`?[32mPROBLEMS?[0m (15)
  ?[33minternal:/tosca/kubernetes/1.0/profile.yaml?[0m
    ?[36mimports[0]?[0m: URL not found: artifacts.yaml
    ?[36mimports[1]?[0m: URL not found: groups.yaml
    ?[36mimports[2]?[0m: URL not found: policies.yaml
  ?[33minternal:/tosca/simple/1.1/profile.yaml?[0m
    ?[36mimports[0]?[0m: URL not found: artifacts.yaml
    ?[36mimports[0]?[0m: URL not found: artifacts.yaml
    ?[36mimports[0]?[0m: URL not found: artifacts.yaml
    ?[36mimports[1]?[0m: URL not found: groups.yaml
    ?[36mimports[1]?[0m: URL not found: groups.yaml
    ?[36mimports[1]?[0m: URL not found: groups.yaml
    ?[36mimports[2]?[0m: URL not found: nodes.yaml
    ?[36mimports[2]?[0m: URL not found: nodes.yaml
    ?[36mimports[2]?[0m: URL not found: nodes.yaml
    ?[36mimports[3]?[0m: URL not found: policies.yaml
    ?[36mimports[3]?[0m: URL not found: policies.yaml
    ?[36mimports[3]?[0m: URL not found: policies.yaml`

**Comment by tliron** [comment]
There is a mismatch between the latest release and the examples on git. If you clone from git, make sure to checkout the right tag. For the latest 0.2 release you probably want to run this:
```
git checkout tags/0.2
```
Alternatively, if you download that zip or tar.gz releases, those will include the examples in the right version.

Please let me know if this works for you.

**Comment by codesnk** [comment]
Thanks for the quick update. I had downloaded the master branch as .zip archive and tried that. I will try again with your tip.

**Comment by codesnk** [comment]
I had some time to try the release version "puccini_0.2_windows_amd64.zip" with the included examples in the zip archive but got the same errors. Wonder if I am doing something wrong.
I tried:
`puccini-tosca compile <path-to-\kubernetes\bookinfo-simple.yaml>`

**Comment by codesnk** [comment]
Too many posts and edits from me, sorry for that, but I got my hands on a Linux machine and there were no problems there, at least with compiling the bookinfo example as above, so it seems the problem is platform specific. Have you tested this on a Windows machine?

**Comment by tliron** [comment]
Thank you for your effort!

No, I have not tested on Windows because I don't have a Windows machine handy. :) But now I will make the effort to make sure it works. Thank you for the bug report.

For now I will close this one and open a new one about Windows.

**Comment by tliron** [comment]
The latest commit fixes the Windows issues.
