### ISSUE TITLE
substitution_filter

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#85]
For the following file:
```
tosca_definitions_version: tosca_simple_yaml_1_3
node_types:
  NS:
    derived_from: tosca.nodes.Root
    properties:
      flavour_id:
        type: string
topology_template:
  substitution_mappings:
    node_type: NS
    substitution_filter:
      properties:
        - flavour_id: { equal: flavor1 }
 ```
puccini produces a problem:
```sh
$ puccini-tosca compile substitution_filter.yaml 
PROBLEMS (1)
  file:.../substitution_filter.yaml
    @12,7 topology_template.substitution_mappings.substitution_filter.properties: "list" instead of "map"
```
According to Section 3.6.5 Node Filter definition of TOSCA 1.3, the example seems correct and no problem should be produced, shouldn't it?

**Comment by tliron** [comment]
You are correct. This is a very odd syntax -- it allows you to specify multiple constraints for a property in two ways: either by listing it twice or by applying a list to it. I think this is a mistake. However, it is what is written in the spec and I will fix Puccini to follow it.
