### ISSUE TITLE
adding a quirk to ignore "URL not found:" problems 

### ISSUE THREAD

**Issue by philippemerle** [tliron/puccini#95]
Given the following template
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
topology_template:
  node_templates:
    n1:
      type: tosca.nodes.Compute
      artifacts:
        a1: an_artifact
```
since v0.20.0, puccini signals the following problem
```sh
$ puccini-tosca compile issue_URL_not_found.yaml 
PROBLEMS (1)
  file:/.../issue_URL_not_found.yaml
    @7,9 topology_template.node_templates["n1"].artifacts["a1"]: URL not found: an_artifact
```

The problem is correct as the `an_artifact` file does not exist.

Moreover, could we have a quirk to not check presence of artifact files?
This new quirk should be added to the etsinfv quirk.

**Comment by tliron** [comment]
By the way, you seem to have discovered a different bug here. In your example you did not give the artifact a type. Puccini should mark this as a problem. I will fix this separately.

**Comment by tliron** [comment]
> By the way, you seem to have discovered a different bug here. In your example you did not give the artifact a type. Puccini should mark this as a problem. I will fix this separately.

I fixed this issue in the separate commit. So the test case you presented here must be fixed by adding a type to the artifact.

**Comment by philippemerle** [comment]
Thank @tliron for the explanation.
1. Replacing `puccini-tosca compile` by `puccini-tosca parse` fully adresses my issue.
2. Sorry I did not see myself that missing the artifact type is an error :-( My own parser signals this problem ;-)
